const data = [
  {
    id: 1,
    image: "./assets/images/card-images/card_1.png",
    tag: "Upcoming",
    title: "Data Science Bootcamp - Graded Datathon",
    state: "Starts in",
    days: "00",
    hours: "15",
    mins: "22",
  },
  {
    id: 2,
    image: "./assets/images/card-images/card_2.png",
    tag: "Upcoming",
    title: "Data Sprint 72 - Butterfly Identification",
    state: "Starts in",
    days: "00",
    hours: "12",
    mins: "34",
  },
  {
    id: 3,
    image: "./assets/images/card-images/card_3.png",
    tag: "Active",
    title: "Data Sprint 71 - Weather Recognition",
    state: "Ends in",
    days: "01",
    hours: "17",
    mins: "10",
  },
  {
    id: 4,
    image: "./assets/images/card-images/card_4.png",
    tag: "Active",
    title: "Data Sprint 70-Airline Passenger Satisfaction",
    state: "Ends in",
    days: "00",
    hours: "11",
    mins: "27",
  },
  {
    id: 5,
    image: "./assets/images/card-images/card_5.png",
    tag: "Past",
    title: "Engineering Graduates Employment Outcomes",
    state: "Ended on",
    date: "16th May'22 09:00 PM",
  },
  {
    id: 6,
    image: "./assets/images/card-images/card_6.png",
    tag: "Past",
    title: "Travel Insurance Claim Prediction",
    state: "Ended on",
    date: "16th May'22 09:00 PM",
  },
];

export default data;
